* Code clean-up [2/5]
  - [ ] break up flowHist into smaller reusable chunks, to facilitate
    stepping through the init process, and redoing individual steps
  - [X] use consistent names for flowHist objects: pick one of fh, self etc
    and replace all the others.
  - [ ] use consistent syntax - pass and return complete flowHist objects,
    rather than individual slots
  - [ ] incorporate flowHist slots into flowFrame objects?
  - [X] use proper named lists for the components

* Features [5/7]
  - [ ] S-phase
  - [X] linearity
    Linearity parameter is now added and functioning properly in the
    ~linearity~ branch. Not sure how to deal with this just yet. The sample
    data ranges from 1.92 -- 2.07. How much is acceptable? Should it be
    used to 'correct' the mean ratios?
  - [X] initial peak detection with smoothing using kza::kz (or FFT?)
    Different smoothing algorithms just shift the trade-offs between
    accuracy and noise in the data. Tried kza:kz, kernalapply, rollapply.
  - [X] export results as a table for saving to disk
  - [ ] save and restore parameter estimates from nls
  - [X] batch processing
  - [X] switch to nlsLM for regressions
